name: 'AMM Package Build'
description: 'Build and publish an AMM package'
inputs:
  token:
    description: 'A Github Personal Access Token'
    required: true
  root:
    description: 'Directory with AMM packages.'
    required: true
    default: '.'
  test:
    description: 'Whether to run tests or not.'
    required: true
    default: 'false'
  local:
    description: 'AMM package is located in this repository (used for the AMM repository itself).'
    required: true
    default: 'false'
  args:
    description: 'Additional arguments for build script'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4"
    - name: Setup luarocks
      uses: leafo/gh-actions-luarocks@v4
    - name: Setup lua dependencies
      run: |
        luarocks install --only-deps $GITHUB_ACTION_PATH/fin_env/loader-dev-1.rockspec >~/luarocks.log 2>&1 || (cat ~/luarocks.log && false)
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Setup AMM
      run: |
        lua $GITHUB_ACTION_PATH/fin_env/loader.lua $FLAGS -- "ammcore.bin.installPackages repo=$GITHUB_REPO tag=$GITHUB_REF logLevel=Trace"
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        FLAGS: ${{ (inputs.local == 'true' || inputs.local == true) && ' ' || '--remote' }}
      working-directory: ${{ inputs.root }}
    - name: Run tests
      if: inputs.test == 'true' || inputs.test == true
      run: |
        lua $GITHUB_ACTION_PATH/fin_env/loader.lua -- "ammtest.bin.main logLevel=Trace"
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      working-directory: ${{ inputs.root }}
    - name: Build package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        lua $GITHUB_ACTION_PATH/fin_env/loader.lua -- "ammcore.bin.buildPackage repo=$GITHUB_REPO package=$GITHUB_REF $ARGS logLevel=Trace"
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        ARGS: ${{ args }}
      working-directory: ${{ inputs.root }}
    - name: Parse tag
      id: parse-tag
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "$GITHUB_REF" | sed -e 's:^refs/tags/::' -e 's:/v.*$::' -e 's:^:name=:' >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        GITHUB_REF: ${{ github.ref }}
    - name: Upload files
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ inputs.root }}/build/${{ steps.parse-tag.outputs.pkg_name }}/ammpackage.json
          ${{ inputs.root }}/build/${{ steps.parse-tag.outputs.pkg_name }}/package
        token: ${{ inputs.token }}
