name: 'AMM Package Build'
description: 'Build and publish an AMM package'
inputs:
  token:
    description: 'A Github Personal Access Token'
    required: true
  root:
    description: 'Directory with AMM packages.'
    required: true
    default: '.'
  test:
    description: 'Whether to run tests or not.'
    required: true
    default: 'false'
  local:
    description: 'AMM package is located in this repository (used for the AMM repository itself).'
    required: true
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Setup lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4"
    - name: Setup luarocks
      uses: leafo/gh-actions-luarocks@v4
    - name: Setup lua dependencies
      run: luarocks install --only-deps $GITHUB_ACTION_PATH/fin-env/loader-dev-1.rockspec
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Setup AMM
      run: |
        lua $GITHUB_ACTION_PATH/fin-env/loader.lua $FLAGS -- "ammcore/bin/installPackages # repo=$GITHUB_REPO tag=$GITHUB_REF logLevel=Debug"
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        FLAGS: ${{ (inputs.local == 'true' || inputs.local == true) && '' || '--remote' }}
      working-directory: ${{ inputs.root }}
    - name: Run tests
      if: inputs.test == 'true' || inputs.test == true
      run: |
        lua $GITHUB_ACTION_PATH/fin-env/loader.lua -- "ammtest/bin/main # repo=$GITHUB_REPO tag=$GITHUB_REF logLevel=Debug"
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
      working-directory: ${{ inputs.root }}
    - name: Build package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        lua $GITHUB_ACTION_PATH/fin-env/loader.lua -- "ammcore/bin/buildPackage # repo=$GITHUB_REPO tag=$GITHUB_REF logLevel=Debug"
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
      working-directory: ${{ inputs.root }}
    - name: Upload files
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ inputs.root }}/build/ammpackage.json
          ${{ inputs.root }}/build/package
        token: ${{ inputs.token }}
